# Generated by Django 3.2.4 on 2021-07-15 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20210715_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='first_name',
            new_name='default_full_name',
        ),
    ]
