# Generated by Django 3.2.4 on 2021-07-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_credit',
            field=models.CharField(default='', max_length=254),
        ),
    ]
