# Generated by Django 3.2.4 on 2021-07-24 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='friendly_name',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='sku',
        ),
    ]
