# Generated by Django 3.2.4 on 2021-07-24 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210724_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_edited',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_posted',
        ),
    ]
