# Generated by Django 3.2.5 on 2021-07-25 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210725_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_edited',
        ),
    ]
