# Generated by Django 3.2.5 on 2021-07-31 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('tagname',), 'verbose_name_plural': 'Tags'},
        ),
    ]
