# Generated by Django 3.2.5 on 2021-08-02 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('sku',), 'verbose_name_plural': 'Categories'},
        ),
    ]
