# Generated by Django 3.2.5 on 2021-08-02 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('blog', '0023_auto_20210802_1217'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='TaggableTags',
        ),
    ]
