# Generated by Django 3.2.5 on 2021-08-02 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_rename_tags_taggabletags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaggableTags',
        ),
    ]
