# Generated by Django 3.2.5 on 2021-08-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('intro', models.CharField(max_length=254)),
                ('prep_time', models.DurationField()),
                ('cook_time', models.DurationField()),
                ('servings', models.IntegerField()),
            ],
        ),
    ]
