# Generated by Django 3.2.5 on 2021-08-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210804_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='total_time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
