# Generated by Django 3.2.5 on 2021-08-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20210809_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
