# Generated by Django 3.2.5 on 2021-08-12 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0010_recipe_vote_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='votes',
            field=models.ManyToManyField(related_name='recipe_post_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
