# Generated by Django 3.2.5 on 2021-08-13 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0012_alter_recipe_directions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='recipe_post_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
