# Generated by Django 3.2.5 on 2021-08-14 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_description'),
        ('recipes', '0013_alter_recipe_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_box',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='box', to='products.product'),
        ),
    ]
