# Generated by Django 3.2.5 on 2021-08-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_remove_recipe_vote_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
