# Generated by Django 3.2.5 on 2021-08-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_recipe_vote_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='mail_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
