# Generated by Django 3.2.5 on 2021-08-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_recipe_mail_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='discount_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
