# Generated by Django 3.2.5 on 2021-08-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_recipe_mail_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='discount_code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
