# Generated by Django 3.2.4 on 2021-06-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210623_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
