# Generated by Django 3.2.4 on 2021-06-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_gluten',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
